language: node_js
node_js:
  - v12
cache: npm
install:
  - npm install
before_script:
  - export TZ=Asia/Shanghai
script:
  - npm run build
  - npm test
  - npm run coveralls
deploy:
  - provider: script
    script: npm run deploy
    skip_cleanup: true
    on:
      branch: master
